name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install qtbase5-dev qt5-qmake

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure
      run: |
        mkdir -p build && cd build
        qmake PREFIX=/usr ..

    - name: Build
      run: |
        cd build
        make
